# Generated by Django 2.1.3 on 2018-11-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='T_password',
            new_name='A_password',
        ),
    ]
