# Generated by Django 2.1.2 on 2018-11-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='T_course',
            field=models.CharField(default='not assigned', max_length=20),
        ),
    ]
