# Generated by Django 2.1.2 on 2018-11-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teachers_t_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='T_slug',
            field=models.SlugField(default='#', max_length=20),
        ),
    ]
