# Generated by Django 2.1.2 on 2018-11-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_teachers_t_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='T_slug',
            new_name='slug',
        ),
    ]
