# Generated by Django 2.1.3 on 2018-11-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_merge_20181118_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='T_email',
            field=models.EmailField(blank=True, default='farazuddin.m17@iiits.in', max_length=254),
        ),
    ]
