# Generated by Django 2.1.2 on 2018-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_auto_20181111_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20), max_length=20),
        ),
    ]
