# Generated by Django 2.1.3 on 2018-11-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_auto_20181118_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='T_course_id',
            field=models.ForeignKey(on_delete=None, to='Student.Courses'),
        ),
    ]
